### ISSUE TITLE
Issue related to fitDTU .calcVcovUnscaled()

### ISSUE THREAD

**Issue by XueyiDong** [statOmics/satuRn#16]
Hi developers,

I used satuRn to do DTU analysis on my dataset, and I received some error when using `testDTU`:
```
Warning in min(zz) : no non-missing arguments to min; returning Inf
Warning in max(zz) : no non-missing arguments to max; returning -Inf
Error in seq.default(lo, up, length = bre) : 
  'from' must be a finite number
```
I have 5 experimental groups in my dataset, but I grab 2 groups to put into SummarizedExperiment object at each run. So there are 5 levels in the group factor, but only samples from 2 levels are present in the SummarizedExperiment object, and the rank of the model is 2.

I've checked the output from `fitDTU` when comparing `designgroup000` vs `designgroup100`, and found out the coefficients from `rowData(sumExp.human)[["fitDTUModels"]][[1]]` looks correct :
```
$coefficients
designgroup000 designgroup025 designgroup050 designgroup075 designgroup100 
     0.5360989             NA             NA             NA      0.3417275 
```

However, the vcovUnsc looks like this, where the values should be related to `designgroup100` but not `designgroup025`:
```
$vcovUnsc
               designgroup000 designgroup025 designgroup050 designgroup075 designgroup100
designgroup000    0.003354025      0.0000000             NA             NA             NA
designgroup025    0.000000000      0.0018827             NA             NA             NA
designgroup050             NA             NA             NA             NA             NA
designgroup075             NA             NA             NA             NA             NA
designgroup100             NA             NA             NA             NA             NA
```
This issue may come from the function `.calcVcovUnscaled`, although I haven't looked into this further.

Hopefully that's useful for you to find out the problem and fix it.

Best regards,
Xueyi

**Comment by jgilis** [comment]
Hi @XueyiDong,

Thank for reporting this and thank you for the very clear documentation on the issue!

The origin of the error is the fact that you will have "empty" factor levels in the `colData` of your `summarizedExperiment` object. Simply removing the empty factor levels manually, e.g. by

```{r}
colData(sumExp) <- droplevels(colData(sumExp))
# alternatively: colData(sumExp)$group <- as.factor(as.character(colData(sumExp)$group))
```

should resolve the issue (please let me know if it doesn't).

I could handle this in satuRn internally as well. However, I am not sure yet which option is best:

1. Perform a `droplevels` call on the `colData` slot internally
2. Adapt the `fitDTU` and `testDTU` functions to correctly match the coefficients even in presence of empty factor levels.

I have implemented the latter in the `emptyLevels` branch of this repository. If you want, you could also use that. However, I am hesitant to merge this into master, because removing the empty levels seems a better strategy.

In your analysis, is there really a need for retaining the empty levels?

Kind regards,


Jeroen

**Comment by XueyiDong** [comment]
Hi Jeroen,

Thanks for your quick reply.

I've manually removed the empty factor levels and it works. Although this issue only happen in rare cases and it's easy to be fixed manually, it's still better for satuRn to be able to handle this.

I agree with you that drop the empty levels would be a better solution. There's no rush implementing this. Thanks for your help!

Best regards,
Xueyi

**Comment by jgilis** [comment]
Hi Xueyi,

Happy to hear it works! I will add the `droplevels` soon and close the issue afterwards.

Good luck with your analyses and don't hesitate to reach out if you would encounter additional issues or if you have suggestions for `satuRn`.

Kind regards,

Jeroen

**Comment by jgilis** [comment]
`satuRn` now should internally handle empty factor levels correctly. Changes have been added to the GitHub master branch, and will be included in the next Bioconductor release!
