### ISSUE TITLE
plotDTU coefficients

### ISSUE THREAD

**Issue by jchang97** [statOmics/satuRn#23]
Hi there,

Thank you so much for this wonderful tool!

I just have a little trouble understanding what I should put for the coefficients for the plotDTU function:
Currently my design matrix looks like : `design <- model.matrix(~ 0 + group + Sex) `

And my contrast: `Contrast1 = group1 - group2, `
```
plots <- satuRn::plotDTU(
    object = sumExp,
    contrast = "Contrast1",
    groups = list(group1, group2),
    coefficients = list(c(0, 0, 1), c(0, 1, 0)),
```

Could you please help me understand this and sorry this is a very naive question! 

Thank you very much :)

**Comment by jgilis** [comment]
Hi @jchang97,

Short answer:

coefficients = list(c(1, 0, as many zeroes as you have other groups,0), c(0, 1, as many zeroes as you have other groups,0)).

Long answer:

Setting up the coefficients in the `plotDTU` function is indeed quite complicated. Essentially, each vector of 0's and 1's toggles off/on parameters from the linear model. So which coefficients you need depends on what you want to visualize, which in turn depends on which effect you want to study.

Based on the code that you provided, I assume you are mainly interested in comparing the `group` variables, and that you are just adding the `Sex` variable as an additional off-target source of variability. _(If this is not the case, i.e., if the effect of `Sex` is something that you actually want to study, for example how the group effect differs between sexes or at the effect of sex within a group, then you would require another model specification)._

So assuming you are focused on the group effects, all you would need to do is put a 1 for the group you want to select, and all zeroes elsewhere. This is because all `group` related coefficients of the generalized linear model already have the interpretation of being corrected for the `Sex` variable. So the `Sex` variable does not need to be switched on explicitly at the plotting stage. 

Hope this helps, I'm still thinking of how the make that function more user-friendly while retaining full flexibility...

Jeroen

**Comment by jchang97** [comment]
Hi Jeroen, 

Thank you for your reply!

Yes, you are absolutely right -  I am only looking at the group variable, and Sex variable is included just to be accounted for in the model. 

So just to double check: 

If I have 20 levels of "group", but in the plotDTU function, I only include the groups involved in contrast1 i.e. group1 and group2 in "groups" (as below), will my coefficients be = list(c(1,0,0), c(0,1,0)) despite having 20 levels of group?

```
plots <- satuRn::plotDTU(
    object = sumExp,
    contrast = "Contrast1",
    groups = list(group1, group2),
    coefficients =  list(c(1,0,0), c(0,1,0))
```

Thank you so much!

**Comment by jgilis** [comment]
Hi @jchang97,

No this is not the case, the `groups` input does not influence the `coefficients` input, so it would still be required to put 18 zeros in between.

For this is example, this looks a bit silly and cumbersome. However, the two inputs not influencing each other is required to retain full flexibility, e.g., for more complex models with interaction effects and continuous covariates.

Jeroen

**Comment by jchang97** [comment]
Great thank you Jeroen! :)
